version: '3.8'

services:
  mongosetup:
    container_name: mongosetup
    image: mongo:4.4
    volumes:
      - ./db/rs-init.sh:/scripts/rs-init.sh
      - ./db/db-setup-entrypoint.sh:/scripts/db-setup-entrypoint.sh
      - ./db/wait-for:/scripts/wait-for
    depends_on:
      - db1
      - db2
      - db3
    restart: "no"
    networks:
      mongors-network:
        ipv4_address: 192.168.0.50
    entrypoint: [ "./scripts/db-setup-entrypoint.sh" ]

  db1:
    container_name: db1
    image: mongo:4.4
    volumes:
      - ./db/data1:/data/db
    networks:
      mongors-network:
        ipv4_address: 192.168.0.51
    ports:
      - 27021:27017
    links:
      - db2
      - db3
    restart: unless-stopped
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  db2:
    container_name: db2
    image: mongo:4.4
    volumes:
      - ./db/data2:/data/db
    networks:
      mongors-network:
        ipv4_address: 192.168.0.52
    ports:
      - 27022:27017
    restart: unless-stopped
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  db3:
    container_name: db3
    image: mongo:4.4
    volumes:
      - ./db/data3:/data/db
    networks:
      mongors-network:
        ipv4_address: 192.168.0.53
    ports:
      - 27023:27017
    restart: unless-stopped
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "dbrs"
      ]

  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    networks:
      mongors-network:
        ipv4_address: 192.168.0.54
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://192.168.33.26:3001/api

  server:
    container_name: server
    depends_on:
      - db1
      - db2
      - db3
      - client
    build: ./server
    ports:
      - 3001:3001
    networks:
      mongors-network:
        ipv4_address: 192.168.0.55
    restart: unless-stopped
    environment:
      - REPLICA_URL=mongodb://db1:27017,db2:27017,db3:27017
      - REPLICA_NAME=dbrs

networks:
  mongors-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/16"
